version: '2'

services:

  server:
    restart: always
    build: ./nginx
    links:
      - backend
    volumes_from:
      - backend
    ports:
      - "80:80"
      - "443:443"

  backend:
    restart: always
    build: .
    env_file: ENV.txt
    links:
      - db
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/static

  db:
    restart: always
    build: ./mysql
    env_file: ENV.txt
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local

  staticfiles:
    driver: local
